# This is a basic workflow to help you get started with Actions

name: API Server Pipeline
on:
  push:
#    branches: ["main"]
      branches: ["master"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm install

  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the files
        uses: actions/checkout@v4

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
          SCRIPT: /
            export PATH=$PATH:/usr/bin

      - name: Create the NPM Files
        run: npm install
